<a href="https://colab.research.google.com/github/tanishachouhan019/Pandas-Data-Analysis-Lab/blob/main/Pandas_class6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 6: GroupBy & Aggregations
Welcome to **Class 6** of our Pandas series. Today we’ll learn how to group data and perform aggregations.

## 1. Concept of Split–Apply–Combine
- **Split** the data into groups based on some criteria.
- **Apply** a function (e.g., sum, mean) to each group.
- **Combine** the results into a new DataFrame or Series.

This is the core idea behind `groupby`.

In [43]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]

}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [44]:
print(df)

avg_salary = df.groupby('Department')['Salary'].mean()  #har deparment ki avgreage salary kyab hai?
print(avg_salary)

count_people = df.groupby('Department')['Employee'].count # har deparment mai kitne log hai?
print(count_people)

multi_stats = df.groupby('Department')['Salary'].agg(['mean', 'min' ,'max'])
print(multi_stats)

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000
Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64
<bound method GroupBy.count of <pandas.core.groupby.generic.SeriesGroupBy object at 0x7f3233e77dd0>>
                    mean    min    max
Department
Finance     61000.000000  58000  65000
HR          51000.000000  50000  52000
IT          72333.333333  70000  75000

## 2. Using `groupby()` with Aggregation Functions
- Use `groupby('col').mean()` or other functions like sum, count, min, max.
- You can also use `agg()` to pass multiple functions at once.

## 3. Multiple Aggregations on Different Columns
- With `agg()`, you can specify different functions for each column.
- Example: `df.groupby('Dept').agg({'Salary':'mean', 'Age':'max'})`.

In [45]:
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [46]:
df = pd.DataFrame(data)
print("Original DataFrame")
print(df)
#departments wise age chiye
avg_age = df.groupby('Department')['Age'].mean()
print(avg_age)

#df.gropby('Department').agg({column:ispe lagna ky hai mean,min,max,count?})
print(df.groupby('Department').agg({'Salary':['mean','min','max'],"Age": ['min','max']}))
df

Original DataFrame
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26
Department
Finance    29.333333
HR         28.500000
IT         31.000000
Name: Age, dtype: float64
                  Salary               Age
                    mean    min    max min max
Department
Finance     61000.000000  58000  65000  26  35
HR          51000.000000  50000  52000  28  29
IT          72333.333333  70000  75000  30  32

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

## 4. Pivot Tables & Crosstab
- `pivot_table()` summarizes data like Excel pivot tables.
- `crosstab()` shows frequency counts of combinations of factors.
- Both are powerful for summarizing and comparing groups.

In [47]:
#df.pivot_table(index='konsa column main h' , values="kya chiye", aggfunc=mean,min,max,count)
df.pivot_table(index='Department', values='Salary',aggfunc='mean')

df.pivot_table(index='Department', values=['Salary','Age'],aggfunc='mean')

#Age group -> 25-30 ,31-35
df['Age_group'] = pd.cut(df['Age'], bins=[25,30,35,40], labels=['25-30','31-35','36-40'])

pd.crosstab(df['Department'],df['Age_group'])

Age_group   25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

## Mini Practice
1. Create a DataFrame with columns: Department, Employee, Salary, Age, City.
2. Group by Department to get average Salary and max Age.
3. Apply multiple aggregations using agg().
4. Create a pivot_table to see mean Salary by Department and City.
5. Build a crosstab for Department vs City.

In [49]:

# 1. Create a DataFrame with columns: Department, Employee, Salary, Age, City
data = {
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26],
    "City": ["New York", "San Francisco", "San Francisco", "London", "London", "New York", "San Francisco", "London"]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# 2. Group by Department to get average Salary and max Age
avg_salary = df.groupby('Department')['Salary'].mean()
max_age = df.groupby('Department')['Age'].max()

print(avg_salary)
print(max_age)

# 3. Apply multiple aggregations using agg()
# Example: mean Salary, max Age per Department
multi_stats = df.groupby('Department').agg({'Salary':['mean','min','max'],"Age": ['min','max']})
print(multi_stats)

# 4. Create a pivot_table to see mean Salary by Department and City
pivot_table = df.pivot_table(index='Department', columns='City', values='Salary', aggfunc='mean')
print(pivot_table)

# 5. Build a crosstab for Department vs City
crosstab = pd.crosstab(df['Department'], df['City'])
print(crosstab)

Original DataFrame:
  Department Employee  Salary  Age           City
0         HR     John   50000   28       New York
1         IT    Sarah   70000   32  San Francisco
2         IT     Mike   72000   30  San Francisco
3    Finance     Anna   65000   27         London
4    Finance      Tom   60000   35         London
5         HR    Laura   52000   29       New York
6         IT    Steve   75000   31  San Francisco
7    Finance     Kate   58000   26         London
Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64
Department
Finance    35
HR         29
IT         32
Name: Age, dtype: int64
                  Salary               Age
                    mean    min    max min max
Department
Finance     61000.000000  58000  65000  26  35
HR          51000.000000  50000  52000  28  29
IT          72333.333333  70000  75000  30  32
City         London  New York  San Francisco
Department
Finance     61000.0       NaN            NaN
HR              NaN   51000.0            NaN
IT              NaN       NaN   72333.333333
City        London  New York  San Francisco
Department
Finance          3         0              0
HR               0         2              0
IT               0         0              3

---
## Summary
- Learned the split–apply–combine concept.
- Used `groupby()` with aggregation functions.
- Applied multiple aggregations to different columns.
- Explored `pivot_table` and `crosstab` for summarizing data.